# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# This playbook includes the other playbooks that configure the cluster and
# allows you to configure it from a single playbook. It is the first playbook to
# call.

---
- import_playbook: "{{ lookup('env', 'PWD') }}/playbooks/cluster_setup_kernel_params.yaml"
- import_playbook: "{{ lookup('env', 'PWD') }}/playbooks/cluster_setup_network.yaml"
- name: Restart all hosts
  hosts: cluster_machines
  tasks:
      - block:
            - name: Restart
              reboot:
            - name: Wait for host to be online
              wait_for_connection:
        when: not apply_network_config
- import_playbook: "{{ lookup('env', 'PWD') }}/playbooks/cluster_setup_ha.yaml"
- import_playbook: "{{ lookup('env', 'PWD') }}/playbooks/cluster_setup_ceph.yaml"
- import_playbook: "{{ lookup('env', 'PWD') }}/playbooks/cluster_setup_libvirt.yaml"
